// Action Types
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

// Canvas Settings Action Types
export const SAVE_CANVAS_SETTINGS = 'SAVE_CANVAS_SETTINGS';
export const SAVE_CANVAS_SETTINGS_SUCCESS = 'SAVE_CANVAS_SETTINGS_SUCCESS';
export const LOAD_CANVAS_SETTINGS = 'LOAD_CANVAS_SETTINGS';
export const FETCH_CANVAS_SETTINGS = 'FETCH_CANVAS_SETTINGS';
export const FETCH_CANVAS_SETTINGS_SUCCESS = 'FETCH_CANVAS_SETTINGS_SUCCESS';
